plugin: aws_ec2
boto_profile: [INSERT HERE]
cache: no
regions: # populate inventory with instances in these regions
  - us-east-2
filters:
  instance-state-name:
    - running
    - pending
# ignores 403 errors rather than failing
strict_permissions: False
hostnames:
  - tag:DNS
  - dns-name
  - private-dns-name

# constructed features may be used to create custom groups
strict: False
keyed_groups:
  - prefix: arch
    key: architecture
  - prefix: aws_az
    key: placement.availability_zone
  - prefix: aws_region
    key: 'placement.availability_zone[:-1]'
  - prefix: instance_type
    key: instance_type
  - prefix: tag
    key: tags
